export const LOCAL_STORAGE_KEY_TASKS = "LOCAL_STORAGE_KEY_TASKS";

//errors
export const LOCAL_STORAGE_UNABLE_TO_RETRIVE_ERROR =
  "LOCAL_STORAGE_UNABLE_TO_RETRIVE_ERROR";

export const LOCAL_STORAGE_ITEM_NOT_EXISTS = "LOCAL_STORAGE_ITEM_NOT_EXISTS";
